apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: hello-kustomize
resources:
- namespace.yaml
- service.yaml
- deployment.yaml
patchesJson6902:
  - target:
      version: v1
      group: apps
      kind: Deployment
      name: bgd
      namespace: hello-kustomize
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/env/0/value
        value: red
