apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-hello
  namespace: argocd
spec:
  destination:
    namespace: argocd-hello
    server: https://192.168.0.215:16443
  project: default
  source:
    path: hello
    repoURL: https://github.com/rezamt/argocd-hello
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
    - CreateNamespace=true